language: python
python:
  - "2.7"
  - "3.5"
git:
  depth: 1
sudo: false
addons:
  apt:
    packages:
    - python-scipy
    - libblas-dev
    - liblapack-dev
    - gfortran
    - python-pip
install:
  - travis_wait pip install -q -r requirements.txt
  - travis_wait pip install -q -r requirements-optional.txt
before_script:
  - python setup.py develop
script: 
  - nosetests mpinterfaces 
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - km468@cornell.edu
    on_success: change
    on_failure: always
