language: python
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - python-scipy
    - python-pip
install:
   - pip install numpy
   - python setup.py develop
script: 
   - nosetests mpinterfaces --with-coverage
   - codecov
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - joshgabriel92@ufl.edu
    on_success: always
    on_failure: always
