language: python
python:
  - "2.7"
  - "3.5"
install:
   - pip install numpy
   - python setup.py develop
script: 
   - nose2 
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - joshgabriel92@ufl.edu
    on_success: always
    on_failure: always
