language: python
python:
  - "2.7"
git:
  depth: 1
sudo: false
env:
  global:
    secure: >
      lodjKpzannHsrfU3YoCXP1Jj380qimYHGNx7biGtUBib/N0Mo94rkRppjNnT5kM4l7jy0nH1X
      azfaLtMjBVejyBj1ivVxqruWmmciW9tJqBamlh56ryS804EAOkCNak4j9tsXS0v1dif4rYH2K
      uxdgUp2ExcXjlsjXw20SRM6ZNjmDFYFXJ7x7NN5ta+fuKVYG1fPxl9dknMBIWuYT0fdV2YgSG
      AE9O6vy9Tc60doMdz7fDxTXaIaTdJGcYQWMe5Dmi1nFPOky6yPfMN0VDARDXWhy7gy2S2Ez2I
      tPgJPg+kW0dQZaOKTtzLbnVwskd3NF2JQlBTs1KmuUZwjKb3GNZk0mmNCOEG3MG/tJACgo/Jm
      sT7Lkfk2FmVs5GpXpUTAC9e9AWNZyjrlz0S4GAmlAsO7SrAdP4YcPbihQ+EzIOB9OTK34chnK
      yOWLjEh7NFpnItNKMAodGkD4uP6005P9OBRWE4l7LSbJVjZISVQIMst5jr20+G9uMf6xnk8I+
      IH1i+0FRSDmC8hkpOOugoD4fN1qx5S9/JpUhZil1iJnHb2Pzk2BsQFl0BT/lLGgDjTG4ZWcry
      IY5g8VchOm3yOLjl/jotCoM9sX3xUksyptHcYOUkEm0oxqqjYUAV94S42ifHNS8ltR7rhZCNc
      Q9dEnOG4MexsZ7cxkqnsWniA/s="
addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - python-scipy
    - python-pip
install:
  - travis_wait pip install -r requirements.txt
script: 
  - python setup.py develop
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mashton@ufl.edu
    on_success: change
    on_failure: always
