language: python
python:
  - "3.5"
env:
  global:
    secure: "VsTWhRM/kOTzUcZixkgKVczznViy2KAQDXlsQKGfdmVzPDNbQ8/YtNqbmNBQ/7usn6vuMDVRFVeePo9ocyBi2vGTjCHGwvVQRSyx3De8A2JPpSB4NwtSgaJHrpzTmQdwjAiEjofE4LytQlSkoFEK0EiOH5hycwm3QlvqG5UuUGJi9Yee33UDAT8FAAx6ZSc6HrYoOjxQ4eQqp7magmXHE1F8+JlUK1Z05AXySY8avw5QtyEOe/9JXg8UuZfIct17V0j593fkkfEd49zqzR+NOlmU2KFDOskPT20ZDkUtZQX/B5F9Q7d/ZrmTF0uc0id4ruLuvRqIRh0rCwv8FfdmN/t7N+TSHIMSuzpOz1nIz5s/p07t5lM1kOuOS3ZA67Q1iu72gEB1UPVzRR7w2bYtOHtmRm2bZNVxSKXyn10l9avr/aXEcMPYT0N/j5Fq6AzHpXWHYda07YzSo12PvUxukwjzMwrYc9aLtL7jw5Bf7NA6DVfFAzuzhJP46epS1YhFOBuosy7E4DxN9mOKP0JtJrb0uu2DpVWTASVKmUuWF52YG8G62gZ4dl5F7v+SIoaxXJUTbLppWY3P+IX1dXEWoS4usTLpij5/kLwMBDed8ejbvSEHYTPq2KmduLIjO4PdwwjtNzCWFYPSz9tKeOEnR4a+AFohTPgpRP94bnhd468="
addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - python-scipy
    - python-pip
install:
   - travis_wait pip install -q numpy
   - travis_wait pip install -q codecov
   - python setup.py develop
   - cp config.yaml mpinterfaces/config_mine.yaml
cache:
   - pip
script: 
   - nosetests mpinterfaces --with-coverage
   - nosetests twod_materials --with-coverage
   - codecov
branches:
  except:
    - gh-pages
    - development
    - bitbucket_dev
notifications:
  email:
    recipients:
      - joshgabriel92@ufl.edu
      - richardghennig@gmail.com
    on_success: always
    on_failure: always
