language: python
python:
  - "2.7"
git:
  depth: 1
sudo: false
addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - python-scipy
    - python-pip
install:
  - travis_wait pip install -r requirements.txt
script: 
  - python setup.py develop
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mashton@ufl.edu
    on_success: change
    on_failure: always
