username: your_uf_hpc_username
mp_api: your_materials_project_api_key
normal_binary: /path/to/vasp/executable
twod_binary: /path/to/2D/vasp/executable
vdw_kernel: /path/to/vdw_kernel.bindat  # Leave as-is if the kernel is hard-coded into VASP
potentials: /path/to/POTCAR/files
queue_system: slurm  # Change to pbs if on a PBS system
