# Configure these settings and then move this
# file to your home directory ('~/config.yaml').
username: your_username_on_hpc
mp_api: your_materials_project_api_key
potentials: /path/to/your/vasp/potentials
