# Configure these settings to your system and profile.
username: your_username_on_hpc
mp_api: your_materials_project_api_key
normal_binary: /path/to/normal/vasp/executable
twod_binary: /path/to/twod/vasp/executable
potentials: /path/to/your/vasp/potentials
